export const mock = {
    count: 12,
    next: null,
    previous: null,
    results: [
        {
            id: "1587772008764",
            type: "aggregated",
            verb: {
                id: 4,
                infinitive: "add",
                past_tense: "added"
            },
            activities: [
                {
                    id: 15877115623950000000003004,
                    type: "normal",
                    verb: {
                        id: 4,
                        infinitive: "add",
                        past_tense: "added"
                    },
                    actor_type: "user",
                    actor: {
                        id: 1,
                        username: "sergio",
                        first_name: "",
                        last_name: "",
                        status: null,
                        description: null,
                        verified: false,
                        private: false,
                        avatar:
                            "https://gravatar.com/avatar/ff35ca0a5f96fec410d7307e9131792e?s=150&d=mm&r=pg",
                        streak: 0,
                        timezone: "America/Puerto_Rico",
                        week_tda: 1,
                        twitter_handle: null,
                        instagram_handle: null,
                        product_hunt_handle: null,
                        github_handle: null,
                        telegram_handle: null,
                        nomadlist_handle: null,
                        bmc_handle: null,
                        header: null,
                        is_staff: true,
                        donor: false,
                        shipstreams_handle: null,
                        website: null,
                        tester: false,
                        is_live: false,
                        digest: true,
                        gold: false,
                        accent: "#00a676",
                        maker_score: 0,
                        dark_mode: false,
                        weekends_off: false,
                        hardcore_mode: false,
                        email_notifications: true
                    },
                    object_type: null,
                    object: null,
                    target_type: null,
                    target: null,
                    created_at: "2020-04-24T06:59:22.395328-04:00"
                },
                {
                    id: 15877116014390000000004004,
                    type: "normal",
                    verb: {
                        id: 4,
                        infinitive: "add",
                        past_tense: "added"
                    },
                    actor_type: "user",
                    actor: {
                        id: 1,
                        username: "sergio",
                        first_name: "",
                        last_name: "",
                        status: null,
                        description: null,
                        verified: false,
                        private: false,
                        avatar:
                            "https://gravatar.com/avatar/ff35ca0a5f96fec410d7307e9131792e?s=150&d=mm&r=pg",
                        streak: 0,
                        timezone: "America/Puerto_Rico",
                        week_tda: 1,
                        twitter_handle: null,
                        instagram_handle: null,
                        product_hunt_handle: null,
                        github_handle: null,
                        telegram_handle: null,
                        nomadlist_handle: null,
                        bmc_handle: null,
                        header: null,
                        is_staff: true,
                        donor: false,
                        shipstreams_handle: null,
                        website: null,
                        tester: false,
                        is_live: false,
                        digest: true,
                        gold: false,
                        accent: "#00a676",
                        maker_score: 0,
                        dark_mode: false,
                        weekends_off: false,
                        hardcore_mode: false,
                        email_notifications: true
                    },
                    object_type: null,
                    object: null,
                    target_type: null,
                    target: null,
                    created_at: "2020-04-24T07:00:01.439309-04:00"
                },
                {
                    id: 15877116208940000000005004,
                    type: "normal",
                    verb: {
                        id: 4,
                        infinitive: "add",
                        past_tense: "added"
                    },
                    actor_type: "user",
                    actor: {
                        id: 1,
                        username: "sergio",
                        first_name: "",
                        last_name: "",
                        status: null,
                        description: null,
                        verified: false,
                        private: false,
                        avatar:
                            "https://gravatar.com/avatar/ff35ca0a5f96fec410d7307e9131792e?s=150&d=mm&r=pg",
                        streak: 0,
                        timezone: "America/Puerto_Rico",
                        week_tda: 1,
                        twitter_handle: null,
                        instagram_handle: null,
                        product_hunt_handle: null,
                        github_handle: null,
                        telegram_handle: null,
                        nomadlist_handle: null,
                        bmc_handle: null,
                        header: null,
                        is_staff: true,
                        donor: false,
                        shipstreams_handle: null,
                        website: null,
                        tester: false,
                        is_live: false,
                        digest: true,
                        gold: false,
                        accent: "#00a676",
                        maker_score: 0,
                        dark_mode: false,
                        weekends_off: false,
                        hardcore_mode: false,
                        email_notifications: true
                    },
                    object_type: null,
                    object: null,
                    target_type: null,
                    target: null,
                    created_at: "2020-04-24T07:00:20.894266-04:00"
                },
                {
                    id: 15877192858710000000018004,
                    type: "normal",
                    verb: {
                        id: 4,
                        infinitive: "add",
                        past_tense: "added"
                    },
                    actor_type: "user",
                    actor: {
                        id: 1,
                        username: "sergio",
                        first_name: "",
                        last_name: "",
                        status: null,
                        description: null,
                        verified: false,
                        private: false,
                        avatar:
                            "https://gravatar.com/avatar/ff35ca0a5f96fec410d7307e9131792e?s=150&d=mm&r=pg",
                        streak: 0,
                        timezone: "America/Puerto_Rico",
                        week_tda: 1,
                        twitter_handle: null,
                        instagram_handle: null,
                        product_hunt_handle: null,
                        github_handle: null,
                        telegram_handle: null,
                        nomadlist_handle: null,
                        bmc_handle: null,
                        header: null,
                        is_staff: true,
                        donor: false,
                        shipstreams_handle: null,
                        website: null,
                        tester: false,
                        is_live: false,
                        digest: true,
                        gold: false,
                        accent: "#00a676",
                        maker_score: 0,
                        dark_mode: false,
                        weekends_off: false,
                        hardcore_mode: false,
                        email_notifications: true
                    },
                    object_type: null,
                    object: null,
                    target_type: null,
                    target: null,
                    created_at: "2020-04-24T09:08:05.871011-04:00"
                },
                {
                    id: 15877634237840000000019004,
                    type: "normal",
                    verb: {
                        id: 4,
                        infinitive: "add",
                        past_tense: "added"
                    },
                    actor_type: "user",
                    actor: {
                        id: 1,
                        username: "sergio",
                        first_name: "",
                        last_name: "",
                        status: null,
                        description: null,
                        verified: false,
                        private: false,
                        avatar:
                            "https://gravatar.com/avatar/ff35ca0a5f96fec410d7307e9131792e?s=150&d=mm&r=pg",
                        streak: 0,
                        timezone: "America/Puerto_Rico",
                        week_tda: 1,
                        twitter_handle: null,
                        instagram_handle: null,
                        product_hunt_handle: null,
                        github_handle: null,
                        telegram_handle: null,
                        nomadlist_handle: null,
                        bmc_handle: null,
                        header: null,
                        is_staff: true,
                        donor: false,
                        shipstreams_handle: null,
                        website: null,
                        tester: false,
                        is_live: false,
                        digest: true,
                        gold: false,
                        accent: "#00a676",
                        maker_score: 0,
                        dark_mode: false,
                        weekends_off: false,
                        hardcore_mode: false,
                        email_notifications: true
                    },
                    object_type: "task",
                    object: {
                        id: 19,
                        event: null,
                        done: false,
                        in_progress: false,
                        content: "sssss",
                        created_at: "2020-04-24T21:23:43.784648-04:00",
                        updated_at: "2020-04-24T21:23:43.784677-04:00",
                        due_at: null,
                        done_at: null,
                        user: {
                            id: 1,
                            username: "sergio",
                            first_name: "",
                            last_name: "",
                            status: null,
                            description: null,
                            verified: false,
                            private: false,
                            avatar:
                                "https://gravatar.com/avatar/ff35ca0a5f96fec410d7307e9131792e?s=150&d=mm&r=pg",
                            streak: 0,
                            timezone: "America/Puerto_Rico",
                            week_tda: 1,
                            twitter_handle: null,
                            instagram_handle: null,
                            product_hunt_handle: null,
                            github_handle: null,
                            telegram_handle: null,
                            nomadlist_handle: null,
                            bmc_handle: null,
                            header: null,
                            is_staff: true,
                            donor: false,
                            shipstreams_handle: null,
                            website: null,
                            tester: false,
                            is_live: false,
                            digest: true,
                            gold: false,
                            accent: "#00a676",
                            maker_score: 0,
                            dark_mode: false,
                            weekends_off: false,
                            hardcore_mode: false,
                            email_notifications: true
                        },
                        project_set: [],
                        praise: 0,
                        attachment: null,
                        comment_count: 0
                    },
                    target_type: null,
                    target: null,
                    created_at: "2020-04-24T21:23:43.784648-04:00"
                },
                {
                    id: 15877720035790000000020004,
                    type: "normal",
                    verb: {
                        id: 4,
                        infinitive: "add",
                        past_tense: "added"
                    },
                    actor_type: "user",
                    actor: {
                        id: 1,
                        username: "sergio",
                        first_name: "",
                        last_name: "",
                        status: null,
                        description: null,
                        verified: false,
                        private: false,
                        avatar:
                            "https://gravatar.com/avatar/ff35ca0a5f96fec410d7307e9131792e?s=150&d=mm&r=pg",
                        streak: 0,
                        timezone: "America/Puerto_Rico",
                        week_tda: 1,
                        twitter_handle: null,
                        instagram_handle: null,
                        product_hunt_handle: null,
                        github_handle: null,
                        telegram_handle: null,
                        nomadlist_handle: null,
                        bmc_handle: null,
                        header: null,
                        is_staff: true,
                        donor: false,
                        shipstreams_handle: null,
                        website: null,
                        tester: false,
                        is_live: false,
                        digest: true,
                        gold: false,
                        accent: "#00a676",
                        maker_score: 0,
                        dark_mode: false,
                        weekends_off: false,
                        hardcore_mode: false,
                        email_notifications: true
                    },
                    object_type: "task",
                    object: {
                        id: 20,
                        event: null,
                        done: false,
                        in_progress: false,
                        content: "Test",
                        created_at: "2020-04-24T23:46:43.579318-04:00",
                        updated_at: "2020-04-24T23:46:43.579346-04:00",
                        due_at: null,
                        done_at: null,
                        user: {
                            id: 1,
                            username: "sergio",
                            first_name: "",
                            last_name: "",
                            status: null,
                            description: null,
                            verified: false,
                            private: false,
                            avatar:
                                "https://gravatar.com/avatar/ff35ca0a5f96fec410d7307e9131792e?s=150&d=mm&r=pg",
                            streak: 0,
                            timezone: "America/Puerto_Rico",
                            week_tda: 1,
                            twitter_handle: null,
                            instagram_handle: null,
                            product_hunt_handle: null,
                            github_handle: null,
                            telegram_handle: null,
                            nomadlist_handle: null,
                            bmc_handle: null,
                            header: null,
                            is_staff: true,
                            donor: false,
                            shipstreams_handle: null,
                            website: null,
                            tester: false,
                            is_live: false,
                            digest: true,
                            gold: false,
                            accent: "#00a676",
                            maker_score: 0,
                            dark_mode: false,
                            weekends_off: false,
                            hardcore_mode: false,
                            email_notifications: true
                        },
                        project_set: [],
                        praise: 0,
                        attachment: null,
                        comment_count: 0
                    },
                    target_type: null,
                    target: null,
                    created_at: "2020-04-24T23:46:43.579318-04:00"
                },
                {
                    id: 15877720054600000000021004,
                    type: "normal",
                    verb: {
                        id: 4,
                        infinitive: "add",
                        past_tense: "added"
                    },
                    actor_type: "user",
                    actor: {
                        id: 1,
                        username: "sergio",
                        first_name: "",
                        last_name: "",
                        status: null,
                        description: null,
                        verified: false,
                        private: false,
                        avatar:
                            "https://gravatar.com/avatar/ff35ca0a5f96fec410d7307e9131792e?s=150&d=mm&r=pg",
                        streak: 0,
                        timezone: "America/Puerto_Rico",
                        week_tda: 1,
                        twitter_handle: null,
                        instagram_handle: null,
                        product_hunt_handle: null,
                        github_handle: null,
                        telegram_handle: null,
                        nomadlist_handle: null,
                        bmc_handle: null,
                        header: null,
                        is_staff: true,
                        donor: false,
                        shipstreams_handle: null,
                        website: null,
                        tester: false,
                        is_live: false,
                        digest: true,
                        gold: false,
                        accent: "#00a676",
                        maker_score: 0,
                        dark_mode: false,
                        weekends_off: false,
                        hardcore_mode: false,
                        email_notifications: true
                    },
                    object_type: "task",
                    object: {
                        id: 21,
                        event: null,
                        done: false,
                        in_progress: false,
                        content: "Test",
                        created_at: "2020-04-24T23:46:45.460626-04:00",
                        updated_at: "2020-04-24T23:46:45.460653-04:00",
                        due_at: null,
                        done_at: null,
                        user: {
                            id: 1,
                            username: "sergio",
                            first_name: "",
                            last_name: "",
                            status: null,
                            description: null,
                            verified: false,
                            private: false,
                            avatar:
                                "https://gravatar.com/avatar/ff35ca0a5f96fec410d7307e9131792e?s=150&d=mm&r=pg",
                            streak: 0,
                            timezone: "America/Puerto_Rico",
                            week_tda: 1,
                            twitter_handle: null,
                            instagram_handle: null,
                            product_hunt_handle: null,
                            github_handle: null,
                            telegram_handle: null,
                            nomadlist_handle: null,
                            bmc_handle: null,
                            header: null,
                            is_staff: true,
                            donor: false,
                            shipstreams_handle: null,
                            website: null,
                            tester: false,
                            is_live: false,
                            digest: true,
                            gold: false,
                            accent: "#00a676",
                            maker_score: 0,
                            dark_mode: false,
                            weekends_off: false,
                            hardcore_mode: false,
                            email_notifications: true
                        },
                        project_set: [],
                        praise: 0,
                        attachment: null,
                        comment_count: 0
                    },
                    target_type: null,
                    target: null,
                    created_at: "2020-04-24T23:46:45.460626-04:00"
                },
                {
                    id: 15877720061900000000022004,
                    type: "normal",
                    verb: {
                        id: 4,
                        infinitive: "add",
                        past_tense: "added"
                    },
                    actor_type: "user",
                    actor: {
                        id: 1,
                        username: "sergio",
                        first_name: "",
                        last_name: "",
                        status: null,
                        description: null,
                        verified: false,
                        private: false,
                        avatar:
                            "https://gravatar.com/avatar/ff35ca0a5f96fec410d7307e9131792e?s=150&d=mm&r=pg",
                        streak: 0,
                        timezone: "America/Puerto_Rico",
                        week_tda: 1,
                        twitter_handle: null,
                        instagram_handle: null,
                        product_hunt_handle: null,
                        github_handle: null,
                        telegram_handle: null,
                        nomadlist_handle: null,
                        bmc_handle: null,
                        header: null,
                        is_staff: true,
                        donor: false,
                        shipstreams_handle: null,
                        website: null,
                        tester: false,
                        is_live: false,
                        digest: true,
                        gold: false,
                        accent: "#00a676",
                        maker_score: 0,
                        dark_mode: false,
                        weekends_off: false,
                        hardcore_mode: false,
                        email_notifications: true
                    },
                    object_type: "task",
                    object: {
                        id: 22,
                        event: null,
                        done: false,
                        in_progress: false,
                        content: "Test",
                        created_at: "2020-04-24T23:46:46.190768-04:00",
                        updated_at: "2020-04-24T23:46:46.190792-04:00",
                        due_at: null,
                        done_at: null,
                        user: {
                            id: 1,
                            username: "sergio",
                            first_name: "",
                            last_name: "",
                            status: null,
                            description: null,
                            verified: false,
                            private: false,
                            avatar:
                                "https://gravatar.com/avatar/ff35ca0a5f96fec410d7307e9131792e?s=150&d=mm&r=pg",
                            streak: 0,
                            timezone: "America/Puerto_Rico",
                            week_tda: 1,
                            twitter_handle: null,
                            instagram_handle: null,
                            product_hunt_handle: null,
                            github_handle: null,
                            telegram_handle: null,
                            nomadlist_handle: null,
                            bmc_handle: null,
                            header: null,
                            is_staff: true,
                            donor: false,
                            shipstreams_handle: null,
                            website: null,
                            tester: false,
                            is_live: false,
                            digest: true,
                            gold: false,
                            accent: "#00a676",
                            maker_score: 0,
                            dark_mode: false,
                            weekends_off: false,
                            hardcore_mode: false,
                            email_notifications: true
                        },
                        project_set: [],
                        praise: 0,
                        attachment: null,
                        comment_count: 0
                    },
                    target_type: null,
                    target: null,
                    created_at: "2020-04-24T23:46:46.190768-04:00"
                },
                {
                    id: 15877720079470000000023004,
                    type: "normal",
                    verb: {
                        id: 4,
                        infinitive: "add",
                        past_tense: "added"
                    },
                    actor_type: "user",
                    actor: {
                        id: 1,
                        username: "sergio",
                        first_name: "",
                        last_name: "",
                        status: null,
                        description: null,
                        verified: false,
                        private: false,
                        avatar:
                            "https://gravatar.com/avatar/ff35ca0a5f96fec410d7307e9131792e?s=150&d=mm&r=pg",
                        streak: 0,
                        timezone: "America/Puerto_Rico",
                        week_tda: 1,
                        twitter_handle: null,
                        instagram_handle: null,
                        product_hunt_handle: null,
                        github_handle: null,
                        telegram_handle: null,
                        nomadlist_handle: null,
                        bmc_handle: null,
                        header: null,
                        is_staff: true,
                        donor: false,
                        shipstreams_handle: null,
                        website: null,
                        tester: false,
                        is_live: false,
                        digest: true,
                        gold: false,
                        accent: "#00a676",
                        maker_score: 0,
                        dark_mode: false,
                        weekends_off: false,
                        hardcore_mode: false,
                        email_notifications: true
                    },
                    object_type: "task",
                    object: {
                        id: 23,
                        event: null,
                        done: false,
                        in_progress: false,
                        content: "Test",
                        created_at: "2020-04-24T23:46:47.947789-04:00",
                        updated_at: "2020-04-24T23:46:47.947815-04:00",
                        due_at: null,
                        done_at: null,
                        user: {
                            id: 1,
                            username: "sergio",
                            first_name: "",
                            last_name: "",
                            status: null,
                            description: null,
                            verified: false,
                            private: false,
                            avatar:
                                "https://gravatar.com/avatar/ff35ca0a5f96fec410d7307e9131792e?s=150&d=mm&r=pg",
                            streak: 0,
                            timezone: "America/Puerto_Rico",
                            week_tda: 1,
                            twitter_handle: null,
                            instagram_handle: null,
                            product_hunt_handle: null,
                            github_handle: null,
                            telegram_handle: null,
                            nomadlist_handle: null,
                            bmc_handle: null,
                            header: null,
                            is_staff: true,
                            donor: false,
                            shipstreams_handle: null,
                            website: null,
                            tester: false,
                            is_live: false,
                            digest: true,
                            gold: false,
                            accent: "#00a676",
                            maker_score: 0,
                            dark_mode: false,
                            weekends_off: false,
                            hardcore_mode: false,
                            email_notifications: true
                        },
                        project_set: [],
                        praise: 0,
                        attachment: null,
                        comment_count: 0
                    },
                    target_type: null,
                    target: null,
                    created_at: "2020-04-24T23:46:47.947789-04:00"
                },
                {
                    id: 15877720087640000000024004,
                    type: "normal",
                    verb: {
                        id: 4,
                        infinitive: "add",
                        past_tense: "added"
                    },
                    actor_type: "user",
                    actor: {
                        id: 1,
                        username: "sergio",
                        first_name: "",
                        last_name: "",
                        status: null,
                        description: null,
                        verified: false,
                        private: false,
                        avatar:
                            "https://gravatar.com/avatar/ff35ca0a5f96fec410d7307e9131792e?s=150&d=mm&r=pg",
                        streak: 0,
                        timezone: "America/Puerto_Rico",
                        week_tda: 1,
                        twitter_handle: null,
                        instagram_handle: null,
                        product_hunt_handle: null,
                        github_handle: null,
                        telegram_handle: null,
                        nomadlist_handle: null,
                        bmc_handle: null,
                        header: null,
                        is_staff: true,
                        donor: false,
                        shipstreams_handle: null,
                        website: null,
                        tester: false,
                        is_live: false,
                        digest: true,
                        gold: false,
                        accent: "#00a676",
                        maker_score: 0,
                        dark_mode: false,
                        weekends_off: false,
                        hardcore_mode: false,
                        email_notifications: true
                    },
                    object_type: "task",
                    object: {
                        id: 24,
                        event: null,
                        done: false,
                        in_progress: false,
                        content: "Test",
                        created_at: "2020-04-24T23:46:48.764912-04:00",
                        updated_at: "2020-04-24T23:46:48.764938-04:00",
                        due_at: null,
                        done_at: null,
                        user: {
                            id: 1,
                            username: "sergio",
                            first_name: "",
                            last_name: "",
                            status: null,
                            description: null,
                            verified: false,
                            private: false,
                            avatar:
                                "https://gravatar.com/avatar/ff35ca0a5f96fec410d7307e9131792e?s=150&d=mm&r=pg",
                            streak: 0,
                            timezone: "America/Puerto_Rico",
                            week_tda: 1,
                            twitter_handle: null,
                            instagram_handle: null,
                            product_hunt_handle: null,
                            github_handle: null,
                            telegram_handle: null,
                            nomadlist_handle: null,
                            bmc_handle: null,
                            header: null,
                            is_staff: true,
                            donor: false,
                            shipstreams_handle: null,
                            website: null,
                            tester: false,
                            is_live: false,
                            digest: true,
                            gold: false,
                            accent: "#00a676",
                            maker_score: 0,
                            dark_mode: false,
                            weekends_off: false,
                            hardcore_mode: false,
                            email_notifications: true
                        },
                        project_set: [],
                        praise: 0,
                        attachment: null,
                        comment_count: 0
                    },
                    target_type: null,
                    target: null,
                    created_at: "2020-04-24T23:46:48.764912-04:00"
                }
            ],
            created_at: "2020-04-24T06:59:22.395328-04:00",
            updated_at: "2020-04-24T23:46:48.764912-04:00"
        },
        {
            id: "1587710742673",
            type: "aggregated",
            verb: {
                id: 5,
                infinitive: "launch",
                past_tense: "launched"
            },
            activities: [
                {
                    id: 15877107426730000000002005,
                    type: "normal",
                    verb: {
                        id: 5,
                        infinitive: "launch",
                        past_tense: "launched"
                    },
                    actor_type: "user",
                    actor: {
                        id: 1,
                        username: "sergio",
                        first_name: "",
                        last_name: "",
                        status: null,
                        description: null,
                        verified: false,
                        private: false,
                        avatar:
                            "https://gravatar.com/avatar/ff35ca0a5f96fec410d7307e9131792e?s=150&d=mm&r=pg",
                        streak: 0,
                        timezone: "America/Puerto_Rico",
                        week_tda: 1,
                        twitter_handle: null,
                        instagram_handle: null,
                        product_hunt_handle: null,
                        github_handle: null,
                        telegram_handle: null,
                        nomadlist_handle: null,
                        bmc_handle: null,
                        header: null,
                        is_staff: true,
                        donor: false,
                        shipstreams_handle: null,
                        website: null,
                        tester: false,
                        is_live: false,
                        digest: true,
                        gold: false,
                        accent: "#00a676",
                        maker_score: 0,
                        dark_mode: false,
                        weekends_off: false,
                        hardcore_mode: false,
                        email_notifications: true
                    },
                    object_type: "product",
                    object: {
                        id: 2,
                        name: "Makerlog",
                        slug: "makerlog",
                        user: 1,
                        team: [],
                        product_hunt: null,
                        twitter: null,
                        website: null,
                        projects: [],
                        launched: true,
                        icon: null,
                        description: "",
                        accent: "#00a676",
                        created_at: "2020-04-23T20:44:18.835566-04:00",
                        launched_at: "2020-04-24T02:45:42.673711-04:00"
                    },
                    target_type: null,
                    target: null,
                    created_at: "2020-04-24T06:45:42.673711-04:00"
                }
            ],
            created_at: "2020-04-24T06:45:42.673711-04:00",
            updated_at: "2020-04-24T06:45:42.673711-04:00"
        },
        {
            id: "1587689058835",
            type: "aggregated",
            verb: {
                id: 4,
                infinitive: "add",
                past_tense: "added"
            },
            activities: [
                {
                    id: 15876890588350000000002004,
                    type: "normal",
                    verb: {
                        id: 4,
                        infinitive: "add",
                        past_tense: "added"
                    },
                    actor_type: "user",
                    actor: {
                        id: 1,
                        username: "sergio",
                        first_name: "",
                        last_name: "",
                        status: null,
                        description: null,
                        verified: false,
                        private: false,
                        avatar:
                            "https://gravatar.com/avatar/ff35ca0a5f96fec410d7307e9131792e?s=150&d=mm&r=pg",
                        streak: 0,
                        timezone: "America/Puerto_Rico",
                        week_tda: 1,
                        twitter_handle: null,
                        instagram_handle: null,
                        product_hunt_handle: null,
                        github_handle: null,
                        telegram_handle: null,
                        nomadlist_handle: null,
                        bmc_handle: null,
                        header: null,
                        is_staff: true,
                        donor: false,
                        shipstreams_handle: null,
                        website: null,
                        tester: false,
                        is_live: false,
                        digest: true,
                        gold: false,
                        accent: "#00a676",
                        maker_score: 0,
                        dark_mode: false,
                        weekends_off: false,
                        hardcore_mode: false,
                        email_notifications: true
                    },
                    object_type: "product",
                    object: {
                        id: 2,
                        name: "Makerlog",
                        slug: "makerlog",
                        user: 1,
                        team: [],
                        product_hunt: null,
                        twitter: null,
                        website: null,
                        projects: [],
                        launched: true,
                        icon: null,
                        description: "",
                        accent: "#00a676",
                        created_at: "2020-04-23T20:44:18.835566-04:00",
                        launched_at: "2020-04-24T02:45:42.673711-04:00"
                    },
                    target_type: null,
                    target: null,
                    created_at: "2020-04-24T00:44:18.835566-04:00"
                }
            ],
            created_at: "2020-04-24T00:44:18.835566-04:00",
            updated_at: "2020-04-24T00:44:18.835566-04:00"
        },
        {
            id: "1587689058835",
            type: "aggregated",
            verb: {
                id: 4,
                infinitive: "add",
                past_tense: "added"
            },
            activities: [
                {
                    id: 15876890588350000000002004,
                    type: "normal",
                    verb: {
                        id: 4,
                        infinitive: "add",
                        past_tense: "added"
                    },
                    actor_type: "user",
                    actor: {
                        id: 1,
                        username: "sergio",
                        first_name: "",
                        last_name: "",
                        status: null,
                        description: null,
                        verified: false,
                        private: false,
                        avatar:
                            "https://gravatar.com/avatar/ff35ca0a5f96fec410d7307e9131792e?s=150&d=mm&r=pg",
                        streak: 0,
                        timezone: "America/Puerto_Rico",
                        week_tda: 1,
                        twitter_handle: null,
                        instagram_handle: null,
                        product_hunt_handle: null,
                        github_handle: null,
                        telegram_handle: null,
                        nomadlist_handle: null,
                        bmc_handle: null,
                        header: null,
                        is_staff: true,
                        donor: false,
                        shipstreams_handle: null,
                        website: null,
                        tester: false,
                        is_live: false,
                        digest: true,
                        gold: false,
                        accent: "#00a676",
                        maker_score: 0,
                        dark_mode: false,
                        weekends_off: false,
                        hardcore_mode: false,
                        email_notifications: true
                    },
                    object_type: "product",
                    object: {
                        id: 2,
                        name: "Makerlog",
                        slug: "makerlog",
                        user: 1,
                        team: [],
                        product_hunt: null,
                        twitter: null,
                        website: null,
                        projects: [],
                        launched: true,
                        icon: null,
                        description: "",
                        accent: "#00a676",
                        created_at: "2020-04-23T20:44:18.835566-04:00",
                        launched_at: "2020-04-24T02:45:42.673711-04:00"
                    },
                    target_type: null,
                    target: null,
                    created_at: "2020-04-24T00:44:18.835566-04:00"
                }
            ],
            created_at: "2020-04-24T00:44:18.835566-04:00",
            updated_at: "2020-04-24T00:44:18.835566-04:00"
        },
        {
            id: "1587689058835",
            type: "aggregated",
            verb: {
                id: 4,
                infinitive: "add",
                past_tense: "added"
            },
            activities: [
                {
                    id: 15876890588350000000002004,
                    type: "normal",
                    verb: {
                        id: 4,
                        infinitive: "add",
                        past_tense: "added"
                    },
                    actor_type: "user",
                    actor: {
                        id: 1,
                        username: "sergio",
                        first_name: "",
                        last_name: "",
                        status: null,
                        description: null,
                        verified: false,
                        private: false,
                        avatar:
                            "https://gravatar.com/avatar/ff35ca0a5f96fec410d7307e9131792e?s=150&d=mm&r=pg",
                        streak: 0,
                        timezone: "America/Puerto_Rico",
                        week_tda: 1,
                        twitter_handle: null,
                        instagram_handle: null,
                        product_hunt_handle: null,
                        github_handle: null,
                        telegram_handle: null,
                        nomadlist_handle: null,
                        bmc_handle: null,
                        header: null,
                        is_staff: true,
                        donor: false,
                        shipstreams_handle: null,
                        website: null,
                        tester: false,
                        is_live: false,
                        digest: true,
                        gold: false,
                        accent: "#00a676",
                        maker_score: 0,
                        dark_mode: false,
                        weekends_off: false,
                        hardcore_mode: false,
                        email_notifications: true
                    },
                    object_type: "product",
                    object: {
                        id: 2,
                        name: "Makerlog",
                        slug: "makerlog",
                        user: 1,
                        team: [],
                        product_hunt: null,
                        twitter: null,
                        website: null,
                        projects: [],
                        launched: true,
                        icon: null,
                        description: "",
                        accent: "#00a676",
                        created_at: "2020-04-23T20:44:18.835566-04:00",
                        launched_at: "2020-04-24T02:45:42.673711-04:00"
                    },
                    target_type: null,
                    target: null,
                    created_at: "2020-04-24T00:44:18.835566-04:00"
                }
            ],
            created_at: "2020-04-24T00:44:18.835566-04:00",
            updated_at: "2020-04-24T00:44:18.835566-04:00"
        },
        {
            id: "1587689058835",
            type: "aggregated",
            verb: {
                id: 4,
                infinitive: "add",
                past_tense: "added"
            },
            activities: [
                {
                    id: 15876890588350000000002004,
                    type: "normal",
                    verb: {
                        id: 4,
                        infinitive: "add",
                        past_tense: "added"
                    },
                    actor_type: "user",
                    actor: {
                        id: 1,
                        username: "sergio",
                        first_name: "",
                        last_name: "",
                        status: null,
                        description: null,
                        verified: false,
                        private: false,
                        avatar:
                            "https://gravatar.com/avatar/ff35ca0a5f96fec410d7307e9131792e?s=150&d=mm&r=pg",
                        streak: 0,
                        timezone: "America/Puerto_Rico",
                        week_tda: 1,
                        twitter_handle: null,
                        instagram_handle: null,
                        product_hunt_handle: null,
                        github_handle: null,
                        telegram_handle: null,
                        nomadlist_handle: null,
                        bmc_handle: null,
                        header: null,
                        is_staff: true,
                        donor: false,
                        shipstreams_handle: null,
                        website: null,
                        tester: false,
                        is_live: false,
                        digest: true,
                        gold: false,
                        accent: "#00a676",
                        maker_score: 0,
                        dark_mode: false,
                        weekends_off: false,
                        hardcore_mode: false,
                        email_notifications: true
                    },
                    object_type: "product",
                    object: {
                        id: 2,
                        name: "Makerlog",
                        slug: "makerlog",
                        user: 1,
                        team: [],
                        product_hunt: null,
                        twitter: null,
                        website: null,
                        projects: [],
                        launched: true,
                        icon: null,
                        description: "",
                        accent: "#00a676",
                        created_at: "2020-04-23T20:44:18.835566-04:00",
                        launched_at: "2020-04-24T02:45:42.673711-04:00"
                    },
                    target_type: null,
                    target: null,
                    created_at: "2020-04-24T00:44:18.835566-04:00"
                }
            ],
            created_at: "2020-04-24T00:44:18.835566-04:00",
            updated_at: "2020-04-24T00:44:18.835566-04:00"
        },
        {
            id: "1587689058835",
            type: "aggregated",
            verb: {
                id: 4,
                infinitive: "add",
                past_tense: "added"
            },
            activities: [
                {
                    id: 15876890588350000000002004,
                    type: "normal",
                    verb: {
                        id: 4,
                        infinitive: "add",
                        past_tense: "added"
                    },
                    actor_type: "user",
                    actor: {
                        id: 1,
                        username: "sergio",
                        first_name: "",
                        last_name: "",
                        status: null,
                        description: null,
                        verified: false,
                        private: false,
                        avatar:
                            "https://gravatar.com/avatar/ff35ca0a5f96fec410d7307e9131792e?s=150&d=mm&r=pg",
                        streak: 0,
                        timezone: "America/Puerto_Rico",
                        week_tda: 1,
                        twitter_handle: null,
                        instagram_handle: null,
                        product_hunt_handle: null,
                        github_handle: null,
                        telegram_handle: null,
                        nomadlist_handle: null,
                        bmc_handle: null,
                        header: null,
                        is_staff: true,
                        donor: false,
                        shipstreams_handle: null,
                        website: null,
                        tester: false,
                        is_live: false,
                        digest: true,
                        gold: false,
                        accent: "#00a676",
                        maker_score: 0,
                        dark_mode: false,
                        weekends_off: false,
                        hardcore_mode: false,
                        email_notifications: true
                    },
                    object_type: "product",
                    object: {
                        id: 2,
                        name: "Makerlog",
                        slug: "makerlog",
                        user: 1,
                        team: [],
                        product_hunt: null,
                        twitter: null,
                        website: null,
                        projects: [],
                        launched: true,
                        icon: null,
                        description: "",
                        accent: "#00a676",
                        created_at: "2020-04-23T20:44:18.835566-04:00",
                        launched_at: "2020-04-24T02:45:42.673711-04:00"
                    },
                    target_type: null,
                    target: null,
                    created_at: "2020-04-24T00:44:18.835566-04:00"
                }
            ],
            created_at: "2020-04-24T00:44:18.835566-04:00",
            updated_at: "2020-04-24T00:44:18.835566-04:00"
        },
        {
            id: "1587689058835",
            type: "aggregated",
            verb: {
                id: 5,
                infinitive: "launch",
                past_tense: "launched"
            },
            activities: [
                {
                    id: 15876890588350000000002005,
                    type: "normal",
                    verb: {
                        id: 5,
                        infinitive: "launch",
                        past_tense: "launched"
                    },
                    actor_type: "user",
                    actor: {
                        id: 1,
                        username: "sergio",
                        first_name: "",
                        last_name: "",
                        status: null,
                        description: null,
                        verified: false,
                        private: false,
                        avatar:
                            "https://gravatar.com/avatar/ff35ca0a5f96fec410d7307e9131792e?s=150&d=mm&r=pg",
                        streak: 0,
                        timezone: "America/Puerto_Rico",
                        week_tda: 1,
                        twitter_handle: null,
                        instagram_handle: null,
                        product_hunt_handle: null,
                        github_handle: null,
                        telegram_handle: null,
                        nomadlist_handle: null,
                        bmc_handle: null,
                        header: null,
                        is_staff: true,
                        donor: false,
                        shipstreams_handle: null,
                        website: null,
                        tester: false,
                        is_live: false,
                        digest: true,
                        gold: false,
                        accent: "#00a676",
                        maker_score: 0,
                        dark_mode: false,
                        weekends_off: false,
                        hardcore_mode: false,
                        email_notifications: true
                    },
                    object_type: "product",
                    object: {
                        id: 2,
                        name: "Makerlog",
                        slug: "makerlog",
                        user: 1,
                        team: [],
                        product_hunt: null,
                        twitter: null,
                        website: null,
                        projects: [],
                        launched: true,
                        icon: null,
                        description: "",
                        accent: "#00a676",
                        created_at: "2020-04-23T20:44:18.835566-04:00",
                        launched_at: "2020-04-24T02:45:42.673711-04:00"
                    },
                    target_type: null,
                    target: null,
                    created_at: "2020-04-24T00:44:18.835566-04:00"
                }
            ],
            created_at: "2020-04-24T00:44:18.835566-04:00",
            updated_at: "2020-04-24T00:44:18.835566-04:00"
        },
        {
            id: "1587689058835",
            type: "aggregated",
            verb: {
                id: 4,
                infinitive: "add",
                past_tense: "added"
            },
            activities: [
                {
                    id: 15876890588350000000002004,
                    type: "normal",
                    verb: {
                        id: 4,
                        infinitive: "add",
                        past_tense: "added"
                    },
                    actor_type: "user",
                    actor: {
                        id: 1,
                        username: "sergio",
                        first_name: "",
                        last_name: "",
                        status: null,
                        description: null,
                        verified: false,
                        private: false,
                        avatar:
                            "https://gravatar.com/avatar/ff35ca0a5f96fec410d7307e9131792e?s=150&d=mm&r=pg",
                        streak: 0,
                        timezone: "America/Puerto_Rico",
                        week_tda: 1,
                        twitter_handle: null,
                        instagram_handle: null,
                        product_hunt_handle: null,
                        github_handle: null,
                        telegram_handle: null,
                        nomadlist_handle: null,
                        bmc_handle: null,
                        header: null,
                        is_staff: true,
                        donor: false,
                        shipstreams_handle: null,
                        website: null,
                        tester: false,
                        is_live: false,
                        digest: true,
                        gold: false,
                        accent: "#00a676",
                        maker_score: 0,
                        dark_mode: false,
                        weekends_off: false,
                        hardcore_mode: false,
                        email_notifications: true
                    },
                    object_type: "product",
                    object: {
                        id: 2,
                        name: "Makerlog",
                        slug: "makerlog",
                        user: 1,
                        team: [],
                        product_hunt: null,
                        twitter: null,
                        website: null,
                        projects: [],
                        launched: true,
                        icon: null,
                        description: "",
                        accent: "#00a676",
                        created_at: "2020-04-23T20:44:18.835566-04:00",
                        launched_at: "2020-04-24T02:45:42.673711-04:00"
                    },
                    target_type: null,
                    target: null,
                    created_at: "2020-04-24T00:44:18.835566-04:00"
                }
            ],
            created_at: "2020-04-24T00:44:18.835566-04:00",
            updated_at: "2020-04-24T00:44:18.835566-04:00"
        },
        {
            id: "1587689058835",
            type: "aggregated",
            verb: {
                id: 4,
                infinitive: "add",
                past_tense: "added"
            },
            activities: [
                {
                    id: 15876890588350000000002004,
                    type: "normal",
                    verb: {
                        id: 4,
                        infinitive: "add",
                        past_tense: "added"
                    },
                    actor_type: "user",
                    actor: {
                        id: 1,
                        username: "sergio",
                        first_name: "",
                        last_name: "",
                        status: null,
                        description: null,
                        verified: false,
                        private: false,
                        avatar:
                            "https://gravatar.com/avatar/ff35ca0a5f96fec410d7307e9131792e?s=150&d=mm&r=pg",
                        streak: 0,
                        timezone: "America/Puerto_Rico",
                        week_tda: 1,
                        twitter_handle: null,
                        instagram_handle: null,
                        product_hunt_handle: null,
                        github_handle: null,
                        telegram_handle: null,
                        nomadlist_handle: null,
                        bmc_handle: null,
                        header: null,
                        is_staff: true,
                        donor: false,
                        shipstreams_handle: null,
                        website: null,
                        tester: false,
                        is_live: false,
                        digest: true,
                        gold: false,
                        accent: "#00a676",
                        maker_score: 0,
                        dark_mode: false,
                        weekends_off: false,
                        hardcore_mode: false,
                        email_notifications: true
                    },
                    object_type: "product",
                    object: {
                        id: 2,
                        name: "Makerlog",
                        slug: "makerlog",
                        user: 1,
                        team: [],
                        product_hunt: null,
                        twitter: null,
                        website: null,
                        projects: [],
                        launched: true,
                        icon: null,
                        description: "",
                        accent: "#00a676",
                        created_at: "2020-04-23T20:44:18.835566-04:00",
                        launched_at: "2020-04-24T02:45:42.673711-04:00"
                    },
                    target_type: null,
                    target: null,
                    created_at: "2020-04-24T00:44:18.835566-04:00"
                }
            ],
            created_at: "2020-04-24T00:44:18.835566-04:00",
            updated_at: "2020-04-24T00:44:18.835566-04:00"
        },
        {
            id: "1587689058835",
            type: "aggregated",
            verb: {
                id: 4,
                infinitive: "add",
                past_tense: "added"
            },
            activities: [
                {
                    id: 15876890588350000000002004,
                    type: "normal",
                    verb: {
                        id: 4,
                        infinitive: "add",
                        past_tense: "added"
                    },
                    actor_type: "user",
                    actor: {
                        id: 1,
                        username: "sergio",
                        first_name: "",
                        last_name: "",
                        status: null,
                        description: null,
                        verified: false,
                        private: false,
                        avatar:
                            "https://gravatar.com/avatar/ff35ca0a5f96fec410d7307e9131792e?s=150&d=mm&r=pg",
                        streak: 0,
                        timezone: "America/Puerto_Rico",
                        week_tda: 1,
                        twitter_handle: null,
                        instagram_handle: null,
                        product_hunt_handle: null,
                        github_handle: null,
                        telegram_handle: null,
                        nomadlist_handle: null,
                        bmc_handle: null,
                        header: null,
                        is_staff: true,
                        donor: false,
                        shipstreams_handle: null,
                        website: null,
                        tester: false,
                        is_live: false,
                        digest: true,
                        gold: false,
                        accent: "#00a676",
                        maker_score: 0,
                        dark_mode: false,
                        weekends_off: false,
                        hardcore_mode: false,
                        email_notifications: true
                    },
                    object_type: "product",
                    object: {
                        id: 2,
                        name: "Makerlog",
                        slug: "makerlog",
                        user: 1,
                        team: [],
                        product_hunt: null,
                        twitter: null,
                        website: null,
                        projects: [],
                        launched: true,
                        icon: null,
                        description: "",
                        accent: "#00a676",
                        created_at: "2020-04-23T20:44:18.835566-04:00",
                        launched_at: "2020-04-24T02:45:42.673711-04:00"
                    },
                    target_type: null,
                    target: null,
                    created_at: "2020-04-24T00:44:18.835566-04:00"
                }
            ],
            created_at: "2020-04-24T00:44:18.835566-04:00",
            updated_at: "2020-04-24T00:44:18.835566-04:00"
        },
        {
            id: "1586626169401",
            type: "aggregated",
            verb: {
                id: 4,
                infinitive: "add",
                past_tense: "added"
            },
            activities: [
                {
                    id: 15865856200690000000001004,
                    type: "normal",
                    verb: {
                        id: 4,
                        infinitive: "add",
                        past_tense: "added"
                    },
                    actor_type: "user",
                    actor: {
                        id: 1,
                        username: "sergio",
                        first_name: "",
                        last_name: "",
                        status: null,
                        description: null,
                        verified: false,
                        private: false,
                        avatar:
                            "https://gravatar.com/avatar/ff35ca0a5f96fec410d7307e9131792e?s=150&d=mm&r=pg",
                        streak: 0,
                        timezone: "America/Puerto_Rico",
                        week_tda: 1,
                        twitter_handle: null,
                        instagram_handle: null,
                        product_hunt_handle: null,
                        github_handle: null,
                        telegram_handle: null,
                        nomadlist_handle: null,
                        bmc_handle: null,
                        header: null,
                        is_staff: true,
                        donor: false,
                        shipstreams_handle: null,
                        website: null,
                        tester: false,
                        is_live: false,
                        digest: true,
                        gold: false,
                        accent: "#00a676",
                        maker_score: 0,
                        dark_mode: false,
                        weekends_off: false,
                        hardcore_mode: false,
                        email_notifications: true
                    },
                    object_type: null,
                    object: null,
                    target_type: null,
                    target: null,
                    created_at: "2020-04-11T06:13:40.069153-04:00"
                },
                {
                    id: 15866261694010000000002004,
                    type: "normal",
                    verb: {
                        id: 4,
                        infinitive: "add",
                        past_tense: "added"
                    },
                    actor_type: "user",
                    actor: {
                        id: 1,
                        username: "sergio",
                        first_name: "",
                        last_name: "",
                        status: null,
                        description: null,
                        verified: false,
                        private: false,
                        avatar:
                            "https://gravatar.com/avatar/ff35ca0a5f96fec410d7307e9131792e?s=150&d=mm&r=pg",
                        streak: 0,
                        timezone: "America/Puerto_Rico",
                        week_tda: 1,
                        twitter_handle: null,
                        instagram_handle: null,
                        product_hunt_handle: null,
                        github_handle: null,
                        telegram_handle: null,
                        nomadlist_handle: null,
                        bmc_handle: null,
                        header: null,
                        is_staff: true,
                        donor: false,
                        shipstreams_handle: null,
                        website: null,
                        tester: false,
                        is_live: false,
                        digest: true,
                        gold: false,
                        accent: "#00a676",
                        maker_score: 0,
                        dark_mode: false,
                        weekends_off: false,
                        hardcore_mode: false,
                        email_notifications: true
                    },
                    object_type: null,
                    object: null,
                    target_type: null,
                    target: null,
                    created_at: "2020-04-11T17:29:29.401360-04:00"
                }
            ],
            created_at: "2020-04-11T06:13:40.069153-04:00",
            updated_at: "2020-04-11T17:29:29.401360-04:00"
        }
    ]
};
